name: Technical Scoping Document
description: Create a document to outline the technical aspects of a new project/idea.
labels: ["Technical Scoping", "Status: Draft"]
body:
  - type: input
    id: project_title
    attributes:
      label: Project Title
      description: Enter the title of the project.
    validations:
      required: true
  - type: input
    id: product_manager
    attributes:
      label: Product Manager
      description: Who is the Product Manager for this project?
    validations:
      required: false
  - type: input
    id: tech_lead_author
    attributes:
      label: Tech Lead / Author
      description: Who is the Tech Lead or Author for this project?
    validations:
      required: false
  - type: input
    id: reviewer
    attributes:
      label: Reviewer
      description: Who will review this technical scoping document?
    validations:
      required: false
  - type: input
    id: engineers_or_squad
    attributes:
      label: Engineers or Squad
      description: Who are the engineers or squads involved in this project?
    validations:
      required: false
  - type: input
    id: product_requirements_link
    attributes:
      label: Link to Product Requirements/Notion Idea
      description: Provide a link to the product requirements document.
    validations:
      required: false
  - type: input
    id: ux_designs_link
    attributes:
      label: (Optional) Link to supporting UX designs
      description: Provide a link to any supporting UX design documents (optional).
    validations:
      required: false
  - type: textarea
    id: product_description
    attributes:
      label: Product Description
      description: Briefly describe what we’re building.
    validations:
      required: false
  - type: textarea
    id: assumptions
    attributes:
      label: Assumptions
      description: List any assumptions you are making in order to complete technical scoping.
      placeholder: I.E. We will not support typeahead autocomplete in the search field.
    validations:
      required: false
  - type: textarea
    id: questions_for_product
    attributes:
      label: Questions for Product
      description: Summarize any outstanding questions necessary to answer in order to shape or finalize technical scoping.
      placeholder: "I.E. Can the user multi-select in the list view?"
    validations:
      required: false
  - type: textarea
    id: new_technologies
    attributes:
      label: New Technologies
      description: Outline any new technologies required to deliver a finished product and why they are necessary.
      placeholder: "I.E. AWS OpenSearch cluster. This will enable a faster search results experience and keep load off of our database."
    validations:
      required: false
  - type: textarea
    id: other_risks
    attributes:
      label: Other Risks
      description: List other risks you foresee in this project and suggest possible solutions.
      placeholder: "I.E. Delivering this product will require a strong emphasis on front-end experience, but our current team is stronger on the back-end. If we cannot borrow resources, could we allot additional time to the front-end components so we can get them right?\nI.E. This project touches our authentication system. This is a sensitive area of the codebase.\n     - Proposed solution: pair with **Engineer** to review plan of action; add reviewers to pull request."
    validations:
      required: false
  - type: textarea
    id: scope_of_work
    attributes:
      label: Scope of Work
      description: Outline the individual tasks necessary for delivery or link to a GitHub Project.
    validations:
      required: false
